[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "burq"
version = "0.2.1"
description = "Write Python. Compile to blazing fast Vanilla JS + HTML."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [{ name = "Daniyal", email = "daniyal@burq.dev" }]
keywords = ["ui", "compiler", "frontend", "python", "vanillajs", "html", "dashboard"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: User Interfaces",
    "Topic :: Internet :: WWW/HTTP",
]
dependencies = [
    "jinja2>=3.1",
    "typer>=0.9",
    "watchdog>=3.0",
    "coloraide>=3.0",
]

[project.urls]
Homepage = "https://burq.dev"
Repository = "https://github.com/itsdaniyalm/burq"
Documentation = "https://burq.dev/docs"

[project.scripts]
burq = "burq.cli.main:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["burq*"]
exclude = ["dev*", "tests*", "test_app*", "runtime*"]