import os
import pathlib
import shutil
from ..app import App
from .html_gen import render_tree, render_base_template, render_page_template
from .js_gen import generate_js
from .css_gen import generate_css


def compile_app(app: App, output_dir: str = "dist"):
    templates_dir = os.path.join(output_dir, "templates")
    static_dir    = os.path.join(output_dir, "static")
    os.makedirs(templates_dir, exist_ok=True)
    os.makedirs(static_dir,    exist_ok=True)

    # ── 1. base.html ──
    _write(templates_dir, "base.html", render_base_template(app))
    print("  ✓ base.html")

    # ── 2. per-page templates ──
    route_entries = []
    for path, fn in app._pages.items():
        page_tree    = app.run_page(path)
        page_content = render_tree(page_tree, app)

        modal_content = ""
        for name in app._modals:
            modal_tree     = app.run_modal(name)
            modal_content += render_tree(modal_tree, app)

        title    = fn.__name__.replace("_", " ").title()
        filename = _path_to_filename(path)
        print(f"  DEBUG path='{path}' has_braces={'{' in path}") 

        _write(templates_dir, filename, render_page_template(page_content, modal_content, url_pattern=path))
        print(f"  ✓ templates/{filename}")

        route_entries.append((path, fn.__name__, filename, title))

    # ── 3. static: tokens.css + burq.js ──
    _write(static_dir, "tokens.css", generate_css(app.theme))
    _write(static_dir, "burq.js",    generate_js(app))
    print("  ✓ tokens.css, burq.js")

    # ── 4. copy layout.css + components.css → static/ ──
    _copy_static(static_dir)

    # ── 5. burq_routes.py ──
    _write(output_dir, "burq_routes.py", _generate_routes(route_entries))
    print("  ✓ burq_routes.py")

    print(f"\n⚡ Burq build complete → {output_dir}/")


def _path_to_filename(path: str) -> str:
    clean = path.strip("/").replace("{", "").replace("}", "").replace("/", "_")
    return (clean or "index") + ".html"


def _generate_routes(entries: list) -> str:
    lines = [
        '"""',
        '⚡ Auto-generated by Burq — https://burq.dev',
        '',
        'Wire up in your FastAPI main.py:',
        '',
        '    from fastapi.staticfiles import StaticFiles',
        '    from dist.burq_routes import router as burq_router',
        '',
        '    app.mount("/static", StaticFiles(directory="dist/static"), name="static")',
        '    app.include_router(burq_router)',
        '"""',
        '',
        'from fastapi import APIRouter, Request',
        'from fastapi.templating import Jinja2Templates',
        '',
        'router    = APIRouter()',
        'import os as _os',
        'templates = Jinja2Templates(directory=_os.path.abspath(_os.path.join(_os.path.dirname(__file__), "templates")))',
        '',
    ]

    for path, fn_name, filename, page_title in entries:
        lines += [
            f'@router.get("{path}")',
            f'def {fn_name}(request: Request):',
            f'    return templates.TemplateResponse(request, "{filename}", {{',
            f'        "page_title": "{page_title}",',
            f'    }})',
            '',
        ]

    return "\n".join(lines)


def _write(directory: str, filename: str, content: str):
    path = os.path.join(directory, filename)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def _copy_static(static_dir: str):
    here   = pathlib.Path(__file__).parent
    ui_dir = here.parent.parent / "dev" / "crm" / "ui"

    for css_file in ["layout.css", "components.css"]:
        src = ui_dir / css_file
        dst = os.path.join(static_dir, css_file)
        if src.exists():
            shutil.copy(src, dst)
            print(f"  ✓ {css_file}")
        else:
            print(f"  ⚠ {css_file} not found at {src}")